### PR TITLE
fix for recent Phoenix.HTML

### PR DESCRIPTION
**Pull request by mayel**

### CODE REVIEW

**Comment by vtm9** [comment]
@khusnetdinov any chance to merge?

**Comment by mayel** [comment]
oops I accidentally pushed commits I intended to submit in a seperate PR, but it doesn't look like this repo is maintained anyway, for anyone reading you're welcome to use our fork directly (in which I've also merged the other open PR): https://github.com/bonfire-networks/phoenix_gon

**Comment by khusnetdinov** [comment]
@mayel Update commit / PR and I will merge it

**Comment by khusnetdinov** [comment]
Could you please create one commit

**Comment by mariusbutuc** [comment]
> Could you please create one commit

@khusnetdinov, I noticed this suggestion surfacing a couple of times. I'm curious: how may we handle this differently in order to keep this project evolving smoothly? As an idea, [configuring a repository to enforce commit squashing for pull requests][1] has worked well for us: it can lower the friction for contributors as well as balance contribution preferences for specific projects. Can this be an alternative solution for a win-win here too?

Here is what this configuration might look like:

Screenshot 2023-03-16 at 17 39 21

What do you think?

  [1]:configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Pull request closed without merging**
